#!/bin/bash

# ============================================================================
# Terraform Documentation Validation Report Generator
# ============================================================================
# 
# This script runs the validation and generates a detailed report with
# timestamps and saves it to a file for review and record-keeping.
# ============================================================================

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VALIDATION_SCRIPT="$SCRIPT_DIR/validate-terraform-docs.sh"
REPORT_DIR="$SCRIPT_DIR/validation-reports"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
REPORT_FILE="$REPORT_DIR/validation_report_$TIMESTAMP.txt"

# Colors for output
BLUE='\033[0;34m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Create reports directory if it doesn't exist
mkdir -p "$REPORT_DIR"

# Function to log with timestamp
log_with_timestamp() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

echo -e "${BLUE}Generating Terraform Documentation Validation Report...${NC}"
echo ""

# Create report header
cat > "$REPORT_FILE" << EOF
============================================================================
                 TERRAFORM DOCUMENTATION VALIDATION REPORT
============================================================================

Report Generated: $(date)
Script Version: 1.0
AWS Profile: aidlc_main
AWS Region: us-west-2
Account ID: 254539707041

============================================================================
                              VALIDATION RESULTS
============================================================================

EOF

# Run validation and capture output
echo "Running validation script..."
if "$VALIDATION_SCRIPT" >> "$REPORT_FILE" 2>&1; then
    VALIDATION_STATUS="PASSED"
    STATUS_COLOR="$GREEN"
else
    VALIDATION_STATUS="FAILED"
    STATUS_COLOR="$RED"
fi

# Add footer to report
cat >> "$REPORT_FILE" << EOF

============================================================================
                              REPORT SUMMARY
============================================================================

Validation Status: $VALIDATION_STATUS
Report File: $REPORT_FILE
Generated By: $(whoami)
System: $(uname -s) $(uname -r)

For detailed analysis of any failures, review the validation results above.
To re-run validation: $VALIDATION_SCRIPT

============================================================================
EOF

# Display results
echo ""
echo -e "${STATUS_COLOR}Validation Status: $VALIDATION_STATUS${NC}"
echo "Report saved to: $REPORT_FILE"
echo ""

# Show recent reports
echo "Recent validation reports:"
ls -lt "$REPORT_DIR"/*.txt 2>/dev/null | head -5 | while read -r line; do
    echo "  $line"
done

# Cleanup old reports (keep last 10)
echo ""
echo "Cleaning up old reports (keeping last 10)..."
ls -t "$REPORT_DIR"/*.txt 2>/dev/null | tail -n +11 | xargs rm -f 2>/dev/null || true

echo ""
echo -e "${BLUE}Report generation completed.${NC}"

# Exit with validation status
if [[ "$VALIDATION_STATUS" == "PASSED" ]]; then
    exit 0
else
    exit 1
fi